#pragma once

#define NO_ACTION_FUNCTION
#define NO_ACTION_MACRO
#define NO_ACTION_ONESHOT
#define NO_ACTION_TAPPING

// #define NO_ACTION_LAYER
#define LAYER_STATE_8BIT
// #define LAYER_STATE_16BIT

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define USB_POLLING_INTERVAL_MS 1
#define DEBOUNCE 5

#define TAP_CODE_DELAY 50

#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0
